### ISSUE TITLE
Can I submit some template format work to this repository?

### ISSUE THREAD

**Issue by aaftio** [gwatts/rootcerts#26]
The code will be modified after use golang format. I think it will be perfect after adjust the template to avoid this.

![image](https://user-images.githubusercontent.com/1856880/112755876-3c945880-9015-11eb-8706-d1b56508a722.png)

![image](https://user-images.githubusercontent.com/1856880/112755896-503fbf00-9015-11eb-96c3-d38cc5cd7e07.png)

![image](https://user-images.githubusercontent.com/1856880/112755905-5e8ddb00-9015-11eb-906f-e80c736e3a6d.png)

![image](https://user-images.githubusercontent.com/1856880/112755919-68afd980-9015-11eb-8b6d-f038bd867bea.png)

**Comment by gwatts** [comment]
I admire your attention to detail!  Feel free to open a PR

**Comment by aaftio** [comment]
@gwatts I had open a PR. Please check it.

**Comment by gwatts** [comment]
Closed by #29
